name: Update data

on:
   schedule:
   - cron: "0 7 * * *"
   #Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Install dependencies
        run: |
          install.packages(c("dataRetrieval", "tidyverse", "shiny", "bslib", "reactable", "readr"))
        shell: Rscript {0}
        
      - name: Update data
        run: |
          source("make_data.R")
        shell: Rscript {0}
        #env:
         # BEARER: ${{ secrets.TWITTER_BEARER }}
        
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push 