name: Update data

on:
  # schedule:
  #  - cron: "0 7 * * *"
  # push:
  #  branches: [ docker ]
  workflow_dispatch:

  
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Install dependencies
        run: |
          install.packages(c("dataRetrieval", "tidyverse", "shiny", "bslib", "reactable", "readr", "rsconnect"))
        shell: Rscript {0}
        
      - name: Update data
        run: |
          source("make_data.R")
        shell: Rscript {0}
        
      - name: deploy
        env:
          # set the shinyapps keys as environment variables
          SHINY_ACC_NAME: ${{ secrets.SHINY_ACC_NAME }}
          TOKEN: ${{ secrets.TOKEN }}
          SECRET: ${{ secrets.SECRET }}
        run: |
          source("deploy.R")
        shell: Rscript {0}  
        
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push 